config/routes.rb
Btma::Application.routes.draw do

  root :to => 'logins#new'
  resources :logins
  resources :teams
  resources :players
  resources :coaches
  resources :games
  resources :batter_game_stats
  resources :pitcher_game_stats
  resources :positions

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

	def new
		@team = Team.new
		@coach = Coach.new
	end

	def create
		coach = Coach.find_by_email(params[:email])

		if coach && coach.authenticate(params[:password])
		  session[:coach_id] = coach.id
		  session[:team_id] = coach.team_id
		  
		  redirect_to ("/teams/#{session[:team_id]}")
		else
		  raise "Login Failed"

		  redirect_to :new_login
		end   
	end

	def show
	end

	def destroy
    session[:coach_id] = nil
    session[:team_id] = nil

    redirect_to :new_login
	end

end

app/views/logins/_new_team.html.erb
<%= form_for @team do |f| %>

	<%= f.label "Team Nickname" %>
	<%= f.text_field :nickname %>

	<%= f.label "City" %>
	<%= f.text_field :city %>

	<%= f.label "Team Logo" %>
	<%= f.text_field :logo %>

	<%= f.submit %>
	
<% end %>

app/views/logins/new.html.erb
<div class="btma_logo">
	<h1>BTMA</h1>
	<p>Baseball Team Management App</p>
</div>

<div class="login_container clear">
	<%= form_tag logins_path, :class => "login" do %>

		<p class="text_field">
		  <%= text_field_tag :email, nil, placeholder: "Email" %>
		</p>
		<p class="text_field clear">
		  <%= password_field_tag :password, nil, placeholder: "Password" %>
		</p> 
		<p class="submit">
			<%= submit_tag "Log In" %>
		</p>

	<% end %>
</div>

<div class="new_team">
	<%= form_for @team, :class => "form" do |f| %>
		<fieldset>
			<legend>Team Info</legend>
			<p>
				<%= f.text_field :nickname, :placeholder => "Team Nickname" %>
			</p>
			<p>
				<%= f.text_field :city, :placeholder => "City" %>
			</p>
			<p>
				<%= f.text_field :state, :placeholder => "State" %>
			</p>
			<!--<p class="text_field">
				<%#= f.text_field :logo, :placeholder => "Logo" %>
			</p>-->
		</fieldset>
		<br />
		<fieldset>
			<legend>Coach Info</legend>
			<%= fields_for @coach do |c| %>
				<p>
					<%= c.text_field :fname, :placeholder => "First Name" %>
				</p>
				<p>
					<%= c.text_field :lname, :placeholder => "Last Name" %>
				</p>
				<p>
					<%= c.text_field :phone, :placeholder => "Phone" %>
				</p>
				<p>
					<%= c.text_field :email, :placeholder => "Email" %>
				</p>
				<p>
					<%= c.password_field :password, :placeholder => "Password" %>
				</p>
				<p>
					<%= c.password_field :password_confirmation, :placeholder => "Password Confirm" %>
				</p>
				<p>
					<%= c.label :manager, "Manager" %>
					<%= c.check_box :manager %>

					<%= c.label :first_base, "1B Coach" %>
					<%= c.check_box :first_base%>

					<%= c.label :third_base, "3B Coach" %>
					<%= c.check_box :third_base %>
				</p>
			<% end %>
		</fieldset>

		<p class="submit">
			<%= f.submit %>
		</p>

	<% end %>

	<div class="no_add_team">Nevermind</div>

</div>

<h3 class="center new_team_link_head">No Team Yet?</h3>
<p class="center new_team_link">Create Team</p>