config/routes.rb
Btma::Application.routes.draw do

  root :to => 'logins#new'
  resources :logins
  resources :teams
  resources :players
  resources :coaches
  resources :games
  resources :batter_game_stats
  resources :pitcher_game_stats
  resources :positions

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :ballpark, :city, :fahr_temp, :game_datetime, :home_team, :weather_id, :opp_nickname, :opp_city, :team_id
  belongs_to :weather
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

	def index
		@games = Game.order("game_datetime").where(:team_id => session[:team_id])
	end

	def show
		@game = Game.find(params[:id])
		@batter_stats = BatterGameStat.where(:game_id => params[:id]).order(:order_in_lineup)
		@pitcher_stats = PitcherGameStat.where(:game_id => params[:id]).order(:pitcher_num)
		@pitcher_game_stat = PitcherGameStat.new
		@batter_game_stat = BatterGameStat.new
		@players = Player.where("team_id = ?", @game.team_id)
		@positions = Position.all
	end

	def new
		@game = Game.new
		@weathers = Weather.all
	end

	def create
		@game = Game.create(params[:game])
		redirect_to ("/games/#{@game.id}")
	end

	def edit
		@game = Game.find(params[:id])
	end

	def update
		@game = Game.find(params[:id])
		@game.update_attributes(params[:game])
	end

	def destroy
		@game = Game.find(params[:id])
		@game.destroy
	end

end

app/views/games/_batter_stat_head.html.erb
<thead>
	<tr>
		<th>#</th>
		<th>Position Players</th>
		<th>Position</th>
		<th>AB</th>
		<th>Hits</th>
		<th>Runs</th>
		<th>2B</th>
		<th>3B</th>
		<th>HR</th>
		<th>RBI</th>
		<th>HB</th>
		<th>BB</th>
		<th>IBB</th>
		<th>SO</th>
		<th>SB</th>
		<th>CS</th>
		<th></th>
	</tr>
</thead>

app/views/games/_game_info.html.erb
<%= form_for @game do |f| %>

	<fieldset>
		<legend>New Game</legend>
		<div class="game_info">

			<%= f.hidden_field :team_id, :value => session[:team_id] %>

			<p>
				<%= f.label :home_team? %>
				<%= f.check_box :home_team %>
			</p>

			<p>
				<%= f.text_field :game_datetime, :class => "datetimepicker", placeholder: "Game Date & Time" %>
			</p>

			<p>
				<%= f.text_field :city, placeholder: "City" %>
			</p>

			<p>
				<%= f.text_field :ballpark, placeholder: "Ballpark" %>
			</p>

			<p>
				<%= f.text_field :opp_nickname, placeholder: "Opponent Nickname" %>
			</p>

			<p>
				<%= f.text_field :opp_city, placeholder: "Opponent City" %>
			</p>

			<p>
				<%= f.text_field :fahr_temp, placeholder: "Temperature" %>
			</p>

			<p>
				<%= f.label :weather_id %>
				<%= f.collection_select(:weather_id, @weathers, :id, :conditions) %>
			</p>

			<p>
				<%= f.submit "Add Game" %>
			</p>

		</div>
	</fieldset>
	
<% end %>

app/views/games/_pitcher_stat_head.html.erb
<thead>
	<tr>
		<th>#</th>
		<th> Add a Pitcher </th>
		<th>Start</th>
		<th>Win</th>
		<th>Loss</th>
		<th>Save</th>
		<th>CG</th>
		<th>SHO</th>
		<th>IP</th>
		<th>Hits</th>
		<th>Runs</th>
		<th>ER</th>
		<th>HR</th>
		<th>HB</th>
		<th>BB</th>
		<th>IBB</th>
		<th>SO</th>
		<th>&nbsp;</th>
	</tr>
</thead>

app/views/games/index.html.erb
<h2>Games</h2>
<table class="stats left">
	<thead>
		<tr>
			<th>Opponent</th>
			<th>Date</th>
			<th>Start Time</th>
		</tr>
	</thead>
	<tbody class="games">
		<% @games.each do |g| %>
			<tr class="game">
				<td><%= link_to g.opp_nickname, game_path(g.id) %></td>
				<td><%= g.game_datetime.strftime("%B %e, %Y") %></td>
				<td><%= g.game_datetime.strftime("%I:%M %p") %></td>
			</tr>
		<% end %>
	</tbody>
</table>
<%= link_to "Add Game", :new_game, :class => "content_button left" %>

app/views/games/new.html.erb
<div class="center">

	<%= render :partial => 'game_info' %>
	
</div>

app/views/games/show.html.erb
<h2>Game vs. <%= @game.opp_nickname %></h2>
<p><%= @game.game_datetime.strftime("%B %e, %Y - %I:%M %p") %></p>
<%= @pitcher_stats.sum(:win) == 1 ? 'WIN' : 'LOSS' %>: <%= @batter_stats.sum(:runs) %> - <%= @pitcher_stats.sum(:runs) %></p>

<table class="stats">

	<%= render :partial => "batter_stat_head" %>

	<tbody class="added_batters">	
		<% @batter_stats.each do |bs| %>
		<tr class="added_batter" id="b<%= bs.order_in_lineup %>">
			<td><%= bs.order_in_lineup %></td>
			<td><%= bs.player.fullname %></td>
			<td><%= bs.position.position %></td>
			<td><%= bs.ab %></td>
			<td><%= bs.hits %></td>
			<td><%= bs.runs %></td>
			<td><%= bs.double %></td>
			<td><%= bs.triple %></td>
			<td><%= bs.hr %></td>
			<td><%= bs.rbi %></td>
			<td><%= bs.hb %></td>
			<td><%= bs.bb %></td>
			<td><%= bs.ibb %></td>
			<td><%= bs.so %></td>
			<td><%= bs.sb %></td>
			<td><%= bs.cs %></td>
			<!--<td><%#= link_to "Edit", batter_game_stat_path(bs.id), :remote => true, :class => "edit" %></td>-->
		</tr>
		<% end %>
	</tbody>

</table>

<%= form_for @batter_game_stat, :remote => true, :class => "add_batter" do |f| %>

	<table class="add_batter_stats">

		<%= render :partial => "batter_stat_head" %>

		<tbody>
			<tr class="batter_form">
				<%= f.hidden_field :game_id, :value => @game.id %>
				<td><%= f.text_field :order_in_lineup, :autofocus => true %></td>
				<td><%= f.collection_select(:player_id, @players, :id, :fullname) %></td>
				<td><%= f.collection_select(:position_id, @positions, :id, :position) %></td>
				<td><%= f.text_field :ab, :value => 0 %></td>
				<td><%= f.text_field :hits, :value => 0 %></td>
				<td><%= f.text_field :runs, :value => 0 %></td>
				<td><%= f.text_field :double, :value => 0 %></td>
				<td><%= f.text_field :triple, :value => 0 %></td>
				<td><%= f.text_field :hr, :value => 0 %></td>
				<td><%= f.text_field :rbi, :value => 0 %></td>
				<td><%= f.text_field :hb, :value => 0 %></td>
				<td><%= f.text_field :bb, :value => 0 %></td>
				<td><%= f.text_field :ibb, :value => 0 %></td>
				<td><%= f.text_field :so, :value => 0 %></td>
				<td><%= f.text_field :sb, :value => 0 %></td>
				<td><%= f.text_field :cs, :value => 0 %></td>
				<td><%= f.submit "Save" %></td>			
			</tr>
		</tbody>
		
	</table>
<% end %>

<div class="add_batter_link content_button">Add Batter</div>
	
</table>
<table class="stats">

	<%= render :partial => "pitcher_stat_head" %>

	<tbody class="added_pitchers">
		<% @pitcher_stats.each do |ps| %>
		<tr class="added_pitcher">
			<td><%= ps.pitcher_num %></td>
			<td><%= ps.player.fullname %></td>
			<td><%= ps.start %></td>
			<td><%= ps.win %></td>
			<td><%= ps.loss %></td>
			<td><%= ps.sv %></td>
			<td><%= ps.cg %></td>
			<td><%= ps.sho %></td>
			<td><%= ps.ip %></td>
			<td><%= ps.hits %></td>
			<td><%= ps.runs %></td>
			<td><%= ps.er %></td>
			<td><%= ps.hr %></td>
			<td><%= ps.hb %></td>
			<td><%= ps.bb %></td>
			<td><%= ps.ibb %></td>
			<td><%= ps.so %></td>
		</tr>
		<% end %>
	</tbody>

</table>

<%= form_for @pitcher_game_stat, :remote => true, :class => "add_pitcher" do |f| %>
	<table class="add_pitcher_stats">

	<%= render :partial => "pitcher_stat_head" %>

		<tbody>
			<tr class="pitcher_form">
				<%= f.hidden_field :game_id, :value => @game.id %>
				<td><%= f.text_field :pitcher_num, :autofocus => true %></td>
				<td><%= f.collection_select(:player_id, @players, :id, :fullname) %></td>
				<td><%= f.check_box :start %></td>
				<td><%= f.check_box :win %></td>
				<td><%= f.check_box :loss %></td>
				<td><%= f.check_box :sv %></td>
				<td><%= f.check_box :cg %></td>
				<td><%= f.check_box :sho %></td>
				<td><%= f.text_field :ip, :value => 0 %></td>
				<td><%= f.text_field :hits, :value => 0 %></td>
				<td><%= f.text_field :runs, :value => 0 %></td>
				<td><%= f.text_field :er, :value => 0 %></td>
				<td><%= f.text_field :hr, :value => 0 %></td>
				<td><%= f.text_field :hb, :value => 0 %></td>
				<td><%= f.text_field :bb, :value => 0 %></td>
				<td><%= f.text_field :ibb, :value => 0 %></td>
				<td><%= f.text_field :so, :value => 0 %></td>
				<td><%= f.submit "Save" %></td>
			</tr>
		</tbody>

	</table>
<% end %>
<div class="add_pitcher_link content_button">Add Pitcher</div>