config/routes.rb
Btma::Application.routes.draw do

  root :to => 'logins#new'
  resources :logins
  resources :teams
  resources :players
  resources :coaches
  resources :games
  resources :batter_game_stats
  resources :pitcher_game_stats
  resources :positions

end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :bats, :dob, :email, :fname, :lname, :phone, :team_id, :throws, :password, :password_confirmation, :fullname

  #has_secure_password
  belongs_to :team
	has_many :positions
	has_many :batter_game_stats
	has_many :pitcher_game_stats
	has_many :parents
	
	#validates :email, :uniqueness => true

	def fullname
		"#{fname} #{lname}"
	end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @players = Player.order(:lname)
    @batter_stats = BatterGameStat.select("
                      SUM(ab) AS sum_ab, 
                      SUM(hits) AS sum_hits, 
                      SUM(runs) AS sum_runs, 
                      SUM(double) AS sum_double, 
                      SUM(triple) AS sum_triple, 
                      SUM(hr) AS sum_hr, 
                      SUM(rbi) AS sum_rbi, 
                      SUM(sb) AS sum_sb, 
                      SUM(cs) AS sum_cs, 
                      SUM(bb) AS sum_bb, 
                      SUM(ibb) AS sum_ibb, 
                      SUM(hb) AS sum_hb, 
                      player_id, 
                      players.fname AS fname,
                      players.lname AS lname,
                      players.team_id AS team_id")
                      .group("batter_game_stats.player_id, fname, lname, team_id")
                      .joins(:player)
                      .order(:lname)
                      .where("players.team_id = ?", session[:team_id])
    @pitcher_stats = PitcherGameStat.select("
                      SUM(start) AS sum_start, 
                      SUM(win) AS sum_win, 
                      SUM(loss) AS sum_loss, 
                      SUM(sv) AS sum_sv, 
                      SUM(cg) AS sum_cg, 
                      SUM(sho) AS sum_sho, 
                      SUM(ip) AS sum_ip, 
                      SUM(hits) AS sum_hits, 
                      SUM(runs) AS sum_runs, 
                      SUM(er) AS sum_er, 
                      SUM(hr) AS sum_hr, 
                      SUM(hb) AS sum_hb, 
                      SUM(bb) AS sum_bb, 
                      SUM(ibb) AS sum_ibb, 
                      SUM(so) AS sum_so, 
                      player_id, 
                      players.fname AS fname,
                      players.lname AS lname,
                      players.team_id AS team_id")
                      .group("pitcher_game_stats.player_id, fname, lname, team_id")
                      .joins(:player)
                      .order(:lname)
                      .where("players.team_id = ?", session[:team_id])
  end

  def show
    @player = Player.find(params[:id])
    @batter_stats = BatterGameStat.where(:player_id => params[:id])
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.create(params[:player])
    @new_players = Player.all(:conditions => ["id NOT IN (?) and id NOT IN (?) and team_id = ?", BatterGameStat.all.map(&:player_id), PitcherGameStat.all.map(&:player_id), params[:player][:team_id]])
    
    respond_to do |format|
      format.html
      format.js 
    end
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    @player.update_attributes(params[:player])

    redirect_to ("/teams/#{params[:player][:team_id]}")
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_list_new_players.html.erb
<% new_players.each do |np| %>
	<tr class="player">
		<td><%= link_to(np.fullname, player_path(np.id)) %></td>
		<td><%= np.bats %></td>
		<td><%= np.throws %></td>
	</tr>
<% end %>

app/views/players/_list_players.html.erb
<% @position_players.each do |pp| %>
	<tr class="player">
		<td><%= link_to(pp.name, player_path(pp.player_id)) %></td>
		<td><%= pp.pos[1...-1] %></td>
		<td><%= pp.bats %></td>
		<td><%= pp.throws %></td>
	</tr>
<% end %>

app/views/players/_new_player.html.erb
<%= form_for @player do |f| %>

	<p>
		<%= f.label "Team ID:*" %>
		<%= f.text_field :team_id %>
	</p>
	<p>
		<%= f.label "First Name" %>
		<%= f.text_field :fname %>
	</p>
	<p>
		<%= f.label "Last Name" %>
		<%= f.text_field :lname %>
	</p>
	<p>
		<%= f.label "Date of Birth:" %>
		<%= f.date_select :dob, 
				start_year: Time.now.year - 70, 
				end_year: Time.now.year - 5, 
				use_short_month: true, 
				order: [:month, :day, :year] %>
	</p>
	<p>
		<%= f.label :phone %>
		<%= f.text_field :phone %>
	</p>
	<p>
		<%= f.label :email %>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :password %>
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
	</p>
	<p>
		<%= f.label :throws %>
		<%= f.select(:throws, options_for_select([['Right', 'Right'], ['Left', 'Left']])) %>
	</p>
	<p>
		<%= f.label :bats %>
		<%= f.select(:bats, options_for_select([['Right', 'Right'], ['Left', 'Left'], ['Switch', 'Switch']])) %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>
<p>*Your manager has to supply you with the "Team ID".</p>

app/views/players/_new_player_row.html.erb
<tr class="player">
	<td><%= @player.fullname %></td>
	<td><%= @player.position %></td>
	<td><%= @player.bats %>/<%= @player.throws %></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
</tr>

app/views/players/create.js.erb
$(".new_players").html("<%= j render :partial => 'list_new_players', :locals => {:new_players => @new_players} %>");
$(".new_player").hide();
$(".new_player")[0].reset();
$(".new_player_link").show();
$(".no_add_player").hide();

app/views/players/edit.html.erb
<h1>Players#edit</h1>
<p>Find me in app/views/players/edit.html.erb</p>

app/views/players/index.html.erb
<h2>Team Stats</h2>
<table class="stats">
	
	<thead>
		<tr>
			<th>Batting</th>
			<th>AB</th>
			<th>Hits</th>
			<th>Runs</th>
			<th>2B</th>
			<th>3B</th>
			<th>HR</th>
			<th>RBI</th>
			<th>SB</th>
			<th>CS</th>
			<th>BB</th>
			<th>IBB</th>
			<th>HB</th>
			<th>AVG</th>
			<th>OBP</th>
		</tr>
	</thead>

	<tbody class="players">
			<% @batter_stats.each do |bs| %>
				<tr class="player">
					<td><%= link_to(bs.fname + ' ' + bs.lname, player_path(bs.player_id)) %></td>
					<td><%= bs.sum_ab %></td>
					<td><%= bs.sum_hits %></td>
					<td><%= bs.sum_runs %></td>
					<td><%= bs.sum_double %></td>
					<td><%= bs.sum_triple %></td>
					<td><%= bs.sum_hr %></td>
					<td><%= bs.sum_rbi %></td>
					<td><%= bs.sum_sb %></td>
					<td><%= bs.sum_cs %></td>
					<td><%= bs.sum_bb %></td>
					<td><%= bs.sum_ibb %></td>
					<td><%= bs.sum_hb %></td>
					<td><%= number_with_precision(((bs.sum_hits.to_d / bs.sum_ab.to_d).to_d), :precision => 3).to_s.sub("0", "") %></td>
					<td><%= number_with_precision((((bs.sum_hits.to_d + bs.sum_bb.to_d) / bs.sum_ab.to_d).to_d), :precision => 3).to_s.sub("0", "") %></td>
				</tr>
			<% end %>
	</tbody>

</table>
<table class="stats">

	<thead>
		<tr>
			<th class="first_col">Pitching</th>
			<th>Starts</th>
			<th>Wins</th>
			<th>Losses</th>
			<th>Saves</th>
			<th>CG</th>
			<th>SHO</th>
			<th>IP</th>
			<th>Hits</th>
			<th>Runs</th>
			<th>ER</th>
			<th>HR</th>
			<th>HB</th>
			<th>BB</th>
			<th>IBB</th>
			<th>SO</th>
			<th>ERA</th>
			<th>WHIP</th>
		</tr>
	</thead>

	<tbody class="players">
		<% @pitcher_stats.each do |ps| %>
				<tr class="player">
					<td><%= link_to(ps.fname + ' ' + ps.lname, player_path(ps.player_id)) %></td>
					<td><%= ps.sum_start %></td>
					<td><%= ps.sum_win %></td>
					<td><%= ps.sum_loss %></td>
					<td><%= ps.sum_sv %></td>
					<td><%= ps.sum_cg %></td>
					<td><%= ps.sum_sho %></td>
					<td><%= ps.sum_ip %></td>
					<td><%= ps.sum_hits %></td>
					<td><%= ps.sum_runs %></td>
					<td><%= ps.sum_er %></td>
					<td><%= ps.sum_hr %></td>
					<td><%= ps.sum_hb %></td>
					<td><%= ps.sum_bb %></td>
					<td><%= ps.sum_ibb %></td>
					<td><%= ps.sum_so %></td>
					<td><%= number_with_precision((((ps.sum_er.to_d / ps.sum_ip.to_d) * 9).to_d), :precision => 2) %></td>
					<td><%= number_with_precision((((ps.sum_bb + ps.sum_hits).to_d / ps.sum_ip.to_d).to_d), :precision => 2) %></td>
				</tr>
			<% end %>

	</tbody>
</table>

app/views/players/new.html.erb
<h2>Become a member of our team:</h2>

<%= render :partial => 'new_player' %>

app/views/players/show.html.erb
<h2><%= @player.fullname %></h2>
<div>
	<p>Born: <%= @player.dob %></p>
	<p>Throws: <%= @player.throws %></p>
	<p>Bats: <%= @player.bats %></p>
</div>

<%= link_to "Delete Player", player_path(@player.id), :method => :delete, :confirm => 'Are you sure you want to delete #{@player.fullname}?', :class => 'right' %>

<table class="stats">
	<thead>
		<tr>
			<!--<th>Year</th>-->
			<th>AB</th>
			<th>Hits</th>
			<th>Runs</th>
			<th>2B</th>
			<th>3B</th>
			<th>HR</th>
			<th>RBI</th>
			<th>SB</th>
			<th>CS</th>
			<th>BB</th>
			<th>IBB</th>
			<th>HB</th>
			<th>AVG</th>
			<th>OBP</th>
		</tr>
	</thead>
	<tbody class="players">
		<tr class="player">
			<!--<td><%#= @batter_stats %></td>-->
			<td><%= @batter_stats.sum(:ab) %></td>
			<td><%= @batter_stats.sum(:hits) %></td>
			<td><%= @batter_stats.sum(:runs) %></td>
			<td><%= @batter_stats.sum(:double) %></td>
			<td><%= @batter_stats.sum(:triple) %></td>
			<td><%= @batter_stats.sum(:hr) %></td>
			<td><%= @batter_stats.sum(:rbi) %></td>
			<td><%= @batter_stats.sum(:sb) %></td>
			<td><%= @batter_stats.sum(:cs) %></td>
			<td><%= @batter_stats.sum(:bb) %></td>
			<td><%= @batter_stats.sum(:ibb) %></td>
			<td><%= @batter_stats.sum(:hb) %></td>
			<td><%= number_with_precision(((@batter_stats.sum(:hits).to_d/@batter_stats.sum(:ab).to_d).to_d), :precision => 3).to_s.sub("0", "") %></td>
			<td><%= number_with_precision((((@batter_stats.sum(:hits) + @batter_stats.sum(:bb)).to_d / @batter_stats.sum(:ab).to_d).to_d), :precision => 3).to_s.sub("0", "") %></td>
		</tr>
	</tbody>
</table>