config/routes.rb
Btma::Application.routes.draw do

  root :to => 'logins#new'
  resources :logins
  resources :teams
  resources :players
  resources :coaches
  resources :games
  resources :batter_game_stats
  resources :pitcher_game_stats
  resources :positions

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BTMA</title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans|Squada+One|Bangers' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body id="<%= params[:controller] %>">
	<% if current_coach %>
		<header class="banner clear">
			<div class="logo left">
				<%= current_team.logo %>
			</div>
			<div class="nickname left">
				<h1><%= current_team.nickname %></h1>
			</div>
			<div class="team_info left">
				<p><%= current_team.city %>, <%= current_team.state %> | Est: <%= current_team.created_at.year %></p>
			</div>
			<nav class="right">
				<%= link_to "Home", team_path(current_team.id) %>
				<%= link_to "Stats", :players %>
				<%= link_to "Games", :games %>
				<%= link_to "Logout", login_path(current_coach.id), :method => :delete %>
			</nav>
		</header>
		<% end %>
	
		<div class="content clear">

			<%= yield %>

		</div>

		<% if current_coach %>
		<footer>
			<p>Team ID: <%= current_team.id %></p>
			<p>Copyright &copy; <%= Time.now.year %> BTMA</p>
		</footer>
	<% end %>
</body>
</html>